CONFIG(debug, debug|release) {
    CONFIGNAME = Debug
    CONFIGPREFFIX = d
} else {
    CONFIGNAME = Release
}

SRCROOTDIR = $$PWD/
PROJDIR = $$SRCROOTDIR/../
COMMONS = $${SRCROOTDIR}/Common/
PROPSCOMMON = $${COMMONS}/propsCommon/

#BUILD PATHS
DESTDIR = $$PROJDIR/bin/$${CONFIGNAME}
LIBDIR = $${PROJDIR}/lib/$${CONFIGNAME}
OBJECTS_DIR = $$PROJDIR/obj/$$CONFIGNAME/$$TARGET

QRPC_INC = $${SRCROOTDIR}/QRpc/
CHAT_COMMON = $${SRCROOTDIR}/ChatCommon/
